=== Abantech/abantech.github.io/demo/SlideSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Name": {
      "type": "string"
    },
    "Version": {
      "type": "string"
    },
    "RoomID": {
      "type": "string"
    },
    "DefaultBackdropURL": {
      "type": "string"
    },
    "Slides": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Location": {
            "type": "string"
          },
          "Is3D": {
            "type": "boolean"
          },
          "Format": {
            "type": "string"
          }
        },
        "required": [
          "Location",
          "Is3D",
          "Format"
        ]
      }
    }
  },
  "required": [
    "Name",
    "Version",
    "RoomID",
    "DefaultBackdropURL",
    "Slides"
  ]
}

=== Abantech/abantech.github.io/demo/AgoraSamplePresentation2.json
{
  "Name": "Demo Presentation",
  "Version": "1.2.3.4",
  "RoomID": "DoorNumber1",
  "DefaultBackdropURL": "https://pbs.twimg.com/profile_images/633688586055913472/3l5HYPgb.jpg",
  "Slides": [
    {
      "Location": "http://abantech.net/demo/werewolf.obj",
      "Is3D": true,
      "Format": "obj"
    },
    {
      "Location": "https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xlp1/v/t1.0-9/14581352_10154609936018114_6059038639917180539_n.jpg?oh=18558ec53c96ae8584671fbf2b0d21bc&oe=58949572&__gda__=1486197036_a46cd8eac5af7d8539f376412ca9c6d3",
      "Is3D": false,
      "Format": "jpeg"
    },
    {
      "Location": "https://scontent-grt2-1.xx.fbcdn.net/v/t1.0-9/14233253_10154539235186248_1735680161014161748_n.jpg?oh=2013a0c295f6e0162f1f425f6c23f4d8&oe=58898751",
      "Is3D": false,
      "Format": "jpeg"
    }
  ]
}
